# Generated by Django 4.2.7 on 2023-11-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rating_beer_rating_user_review_beer_review_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('2XL', 'Doulbe Extra Large')], default='L', max_length=3)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='beers',
            field=models.ManyToManyField(to='main_app.beer'),
        ),
        migrations.AddField(
            model_name='order',
            name='merch',
            field=models.ManyToManyField(to='main_app.merch'),
        ),
    ]
