# Generated by Django 4.2.7 on 2023-11-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_beer_title_alter_merch_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='image',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.beer')),
            ],
        ),
    ]
