# Generated by Django 4.2.7 on 2023-11-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_image_delete_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
